version: '3.5'
services:

  dev-db:
    image: postgres:13
    restart: always # options are [always | no | unless-stopped | on-failure[:max-retries] ] 
    container_name: postgres
    networks:
      - freecodecamp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5434:5432

  test-db:
    image: postgres:13
    container_name: test-postgres
    networks:
      - freecodecamp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5435:5432
networks:
  freecodecamp:
